title: gw2acr Guide
description: A practical guide to designing Automated Combat Routines (ACRs) in gw2acr
baseurl: ""
url: ""

remote_theme: just-the-docs/just-the-docs
color_scheme: dark

search_enabled: true
heading_anchors: true
back_to_top: true
back_to_top_text: "Back to top"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

footer_content: >
  <p>
    gw2acr documentation â€” focused on decision logic, not scripts.
  </p>

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

exclude:
  - README.md
  - .gitignore
